name: 🧪 Run Laravel Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testing
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --host=127.0.0.1 --user=root --password=root"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v3

      - name: 🛠 Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, pdo, pdo_mysql, bcmath
          coverage: none

      - name: ⚡ Cache Composer Dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: composer-${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: composer-${{ runner.os }}-

      - name: 📦 Install PHP Dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: ⚡ Cache Node Modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: npm-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: npm-${{ runner.os }}-

      - name: 🛠 Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: 📦 Install NPM Dependencies
        run: npm install

      - name: ⚡ Build Frontend Assets
        run: npm run build # Use build instead of dev for production

      - name: 🛠 Setup Environment File
        run: cp .env.example .env

      - name: 🔑 Generate Application Key
        run: php artisan key:generate

      - name: 🛠 Run Migrations
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: testing
          DB_USERNAME: root
          DB_PASSWORD: root
          DB_PORT: 3306
          DB_HOST: 127.0.0.1
        run: php artisan migrate --force

      - name: ✅ Run Laravel Tests
        run: php artisan test
